openapi: 3.0.0
servers:
  - description: Cluster Endpoint
    url: /api
info:
  description: Hospital Employee Administration for Web-In-Cloud system
  version: "1.0.0"
  title: Employee List Api
  contact:
    email: xbelake@stuba.sk
  license:
    name: CC BY 4.0
    url: "https://creativecommons.org/licenses/by/4.0/"
tags:
  - name: employeeList
    description: Employee List API
  - name: hospitalRoles
    description: Employee role in the hospital
paths:
  "/employee-list/{hospitalId}/entries":
    post:
      tags:
        - hospitalEmployeeList
      summary: Saves new entry into employee list
      operationId: createEmployeeListEntry
      description: Use this method to store new entry into the mployee list.
      parameters:
        - in: path
          name: hospitalId
          description: pass the id of the particular hospital
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmployeeListEntry"
            examples:
              request-sample:
                $ref: "#/components/examples/EmployeeListEntryExample"
        description: Employee list entry to store
        required: true
      responses:
        "200":
          description: >-
            List of employee in hospital
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmployeeListEntry"
              examples:
                updated-response:
                  $ref: "#/components/examples/EmployeeListEntryExample"
        "400":
          description: Missing mandatory properties of input object.
        "404":
          description: Hospital with such ID does not exists
        "409":
          description: Entry with the specified id already exists
    get:
      tags:
        - hospitalEmployeeList
      summary: Provides the hospital employee list
      operationId: getEmployeeListEntries
      description: By using hospitalId you get list of entries in hospital employee list
      parameters:
        - in: path
          name: hospitalId
          description: pass the id of the particular hospital
          required: true
          schema:
            type: string
      responses:
        "200":
          description: value of the employee list entries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/EmployeeListEntry"
              examples:
                response:
                  $ref: "#/components/examples/EmployeeListEntriesExample"
        "404":
          description: Hospital with such ID does not exist
  "/employee-list/{hospitalId}/entries/{entryId}":
    get:
      tags:
        - hospitalEmployeeList
      summary: Provides details about employee list entry
      operationId: getEmployeeListEntry
      description: >-
        By using hospitalId and entryId you can details of particular entry
        item hospital.
      parameters:
        - in: path
          name: hospitalId
          description: pass the id of the particular hospital
          required: true
          schema:
            type: string
        - in: path
          name: entryId
          description: pass the id of the particular entry in the employee list
          required: true
          schema:
            type: string
      responses:
        "200":
          description: value of the employee list entries
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmployeeListEntry"
              examples:
                response:
                  $ref: "#/components/examples/EmployeeListEntryExample"
        "404":
          description: Hospital or Entry with such ID does not exists
    put:
      tags:
        - hospitalEmployeeList
      summary: Updates specific entry
      operationId: updateEmployeeListEntry
      description: Use this method to update content of the employee list entry.
      parameters:
        - in: path
          name: hospitalId
          description: pass the id of the particular hospital
          required: true
          schema:
            type: string
        - in: path
          name: entryId
          description: pass the id of the particular entry in the employee list
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmployeeListEntry"
            examples:
              request:
                $ref: "#/components/examples/EmployeeListEntryExample"
        description: Waiting list entry to update
        required: true
      responses:
        "200":
          description: >-
            value of the employee list entry with re-computed estimated time of
            hospital entry
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmployeeListEntry"
              examples:
                response:
                  $ref: "#/components/examples/EmployeeListEntryExample"
        "403":
          description: >-
            Value of the entryID and the data id is mismatching. Details are
            provided in the response body.
        "404":
          description: Hospital or Entry with such ID does not exists
    delete:
      tags:
        - hospitalEmployeeList
      summary: Deletes specific entry
      operationId: deleteEmployeeListEntry
      description: Use this method to delete the specific entry from the employee list.
      parameters:
        - in: path
          name: hospitalId
          description: pass the id of the particular hospital
          required: true
          schema:
            type: string
        - in: path
          name: entryId
          description: pass the id of the particular entry in the employee list
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Item deleted
        "404":
          description: Hospital or Entry with such ID does not exists
  "/employee-list/{hospitalId}/role":
    get:
      tags:
        - hospitalRoles
      summary: Provides the list of roles associated with hospital
      operationId: getRoles
      description: By using hospitalId you get list of predefined roles
      parameters:
        - in: path
          name: hospitalId
          description: pass the id of the particular hospital
          required: true
          schema:
            type: string
      responses:
        "200":
          description: value of the predefined roles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Role"
              examples:
                response:
                  $ref: "#/components/examples/RolesListExample"
        "404":
          description: Hospital with such ID does not exists
components:
  schemas:
    EmployeeListEntry:
      type: object
      required: [ id ]
      properties:
        id:
          type: string
          example: x321ab3
          description: Unique id of the entry in this employee list
        name:
          type: string
          example: Jožko Púčik
          description: Name of employee in employee list
        role:
          $ref: "#/components/schemas/Role"
      example:
        $ref: "#/components/examples/EmployeeListEntryExample"
    Role:
      description: "Describes employee position in hospital"
      required:
        - value
      properties:
        value:
          type: string
          example: Doctor
        code:
          type: string
          example: subfebrilia
      example:
        $ref: "#/components/examples/RoleExample"
  examples:
    RolesListExample:
      summary: Sample of GP hospital roles
      description: |
        Example list of possible
      value:
        - value: Doctor
          code: subfebrilia
        - value: Nurse
          code: nausea
        - value: Director
          code: followup
        - value: Administration
          code: administration
        - value: Economist
          code: blood-test
    EmployeeListEntryExample:
      summary: Ľudomír Zlostný employee
      description: |
        Entry represents a employee working in the hospital
      value:
        id: x321ab3
        name: Ľudomír Zlostný
        role:
          value: Nurse
          code: nausea
    RoleExample:
      summary: Roles
      description: list of few roles that can be chosen to employee
      value:
        valuee: Doctor
        code: subfebrilia
    EmployeeListEntriesExample:
      summary: List of employees
      description: |
        Example employee list containing 2 employee
      value:
        - id: x321ab3
          name: Jožko Púčik
          role:
            value: Doctor
            code: subfebrilia
        - id: x321ab4
          name: Ferdinand Trety
          role:
            value: Nurse
            code: nausea
